### ISSUE TITLE
Example for Radio field

### ISSUE THREAD

**Issue by filip-dot-cube** [AckeeCZ/mateus#11]
Cant use it out of the box as in example and its not very clear how to do so. Heres my suggestion:
 `<RadioField
        name={name}
        options={[
                { label: 'Kenny', value: 'orange' },
                { label: 'Cartman', value: 'fat' },
                { label: 'Stan', value: 'blue' },
                { label: 'Kyle', value: 'green' },
            ]} 
    />`

**Comment by horaklukas** [comment]
The repository is being deprecated
